version: '3'
services:
  articles-db:
      environment:
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_USER: $POSTGRES_USER
        DB_PASSWORD: $ARTICLES_DB_PASSWORD
        DB_USER: $ARTICLES_DB_USER
        DB_NAME: $POSTGRES_DB_NAME
        DB_SCHEMA: $ARTICLES_DB_SCHEMA
      image: love-article-postgres
      restart: always
      build: love-article-articles-service/db
      ports:
        - $ARTICLES_DB_PORT:5432
        
  favorites-db:
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      DB_PASSWORD: $FAVORITES_DB_PASSWORD
      DB_USER: $FAVORITES_DB_USER
      DB_NAME: $POSTGRES_DB_NAME
      DB_SCHEMA: $FAVORITES_DB_SCHEMA
    image: love-favorites-postgres
    restart: always
    build: love-article-favorites-service/db
    ports:
      - $FAVORITES_DB_PORT:5432

        